// <auto-generated>
// Rewired Constants
// This list was generated on 10/31/2019 12:53:33 AM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Take a Picture")]
        public const int Take_Photo = 0;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Walk Forward & Backward")]
        public const int Walk = 1;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Strafe Left & Right")]
        public const int Strafe = 2;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Toggle Whether in Camera Mode")]
        public const int Toggle_Camera = 3;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Look Left & Right")]
        public const int Look_Horizontal = 4;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Look Up & Down")]
        public const int Look_Vertical = 5;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Toggle Whether Game Is Paused")]
        public const int Toggle_Pause = 6;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Toggle Sprinting")]
        public const int Sprint = 7;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Save the last photo taken to file")]
        public const int Save_Photo = 8;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "UI Vertical")]
        public const int UI_Vertical = 9;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "UI Horizontal")]
        public const int UI_Horizontal = 10;
    }
    public static partial class Category {
        public const int Default = 0;
    }
    public static partial class Layout {
        public static partial class Joystick {
            public const int Default = 0;
        }
        public static partial class Keyboard {
            public const int Default = 0;
        }
        public static partial class Mouse {
            public const int Default = 0;
        }
        public static partial class CustomController {
            public const int Default = 0;
        }
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int System = 9999999;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player0")]
        public const int Player0 = 0;
    }
    public static partial class CustomController {
    }
    public static partial class LayoutManagerRuleSet {
    }
    public static partial class MapEnablerRuleSet {
    }
}
